const assert = require("node:assert/strict")
const { normalizeSalesSettings, paymentQuote, vipDiscountPercent, vipLevelForSpend } = require("./server")

assert.equal(vipLevelForSpend(0), "vip1")
assert.equal(vipLevelForSpend(359.99), "vip1")
assert.equal(vipLevelForSpend(360), "vip2")
assert.equal(vipLevelForSpend(899.99), "vip2")
assert.equal(vipLevelForSpend(900), "vip3")
assert.equal(vipDiscountPercent("vip1"), 0)
assert.equal(vipDiscountPercent("vip2"), 5)
assert.equal(vipDiscountPercent("vip3"), 10)

const quote = paymentQuote("basic-30", "save10", "SAVE10:10", "vip2")
assert.equal(quote.originalAmount, 39)
assert.equal(quote.discountAmount, 3.9)
assert.equal(quote.vipDiscountAmount, 1.75)
assert.equal(quote.subtotal, 33.35)
assert.equal(quote.taxAmount, 1)
assert.equal(quote.amount, 34.35)

const unlimitedQuote = paymentQuote("ultra-unlimited-180")
assert.equal(unlimitedQuote.traffic, "无限流量")
assert.equal(unlimitedQuote.devices, 3)
assert.deepEqual(unlimitedQuote.cycles.map(cycle => cycle.optionId), ["ultra-unlimited-30", "ultra-unlimited-90", "ultra-unlimited-180", "ultra-unlimited-360"])
assert.equal(paymentQuote("basic-unlimited-30").originalAmount, 79)
assert.equal(paymentQuote("pro-unlimited-30").originalAmount, 95)
assert.equal(paymentQuote("ultra-unlimited-30").originalAmount, 129)

const monthlyCoupon = [{ id: "monthly", code: "MONTHLY10", percent: 10, enabled: true, applicableGroups: ["pro"], applicableDurations: ["monthly"], totalLimit: 0, perAccountLimit: 0 }]
assert.equal(paymentQuote("pro-30", "MONTHLY10", monthlyCoupon).discountPercent, 10)
assert.throws(() => paymentQuote("basic-30", "MONTHLY10", monthlyCoupon), /当前套餐/)
assert.throws(() => paymentQuote("pro-90", "MONTHLY10", monthlyCoupon), /计费周期/)

const couponSettings = normalizeSalesSettings({ coupons: [{ code: "NEW10", percent: 10, applicableGroups: ["basic"], applicableDurations: ["monthly"], totalLimit: 100, perAccountLimit: 1 }] })
assert.deepEqual(couponSettings.coupons[0].applicableGroups, ["basic"])
assert.deepEqual(couponSettings.coupons[0].applicableDurations, ["monthly"])
assert.equal(couponSettings.coupons[0].totalLimit, 100)
assert.equal(couponSettings.coupons[0].perAccountLimit, 1)
assert.throws(() => normalizeSalesSettings({ coupons: [{ code: "BAD10", percent: 10, totalLimit: -1 }] }), /总数量限制/)
